### ISSUE TITLE
RasPyCam crashes with RPi Wide angle camera v3 on Pi0 W v1

### ISSUE THREAD

**Issue by hogwell** [Windermere-Technology/RasPyCam#1]
### Description

I can't get the rpipycam module to run longer than a few seconds with my v3 wide angle autofocus camera.

### Steps to Reproduce

After installing the software per the instructions on a PiZeroW running bullseye, I ran raspycam using:
sudo raspimjpeg

It shows in the ps ax task list for a little while, then crashes with the following log:

Starting RasPyCam main process...
[{'Model': 'imx708_wide', 'Location': 2, 'Rotation': 0, 'Id': '/base/soc/i2c0mux/i2c@1/imx708@1a'}]
Traceback (most recent call last):
  File "/opt/vc/bin/raspycam/main.py", line 36, in <module>
    run()  # pragma: no cover
  File "/opt/vc/bin/raspycam/main.py", line 32, in run
    main(args)
  File "/opt/vc/bin/raspycam/main.py", line 24, in main
    start_background_process(config_filepath)
  File "/opt/vc/bin/raspycam/core/process.py", line 648, in start_background_process
    CameraCoreModel.main_camera = c["Num"]
KeyError: 'Num'

### Expected Behavior

The module should stay running and accept commands from the RPi_Web_Cam_Interface front end.

### Additional Information (Optional)

See the log file above.

### Pi Model

Zero

### Operating System

Raspberry Pi OS Bullseye (11.x)

### Checks

- [X] I have not found any related issues
- [X] I have updated to the latest version
- [ ] I want to contribute a fix

**Comment by hogwell** [comment]
It turns out this seems to be caused by the version of picamera2 that is included in the latest bullseye release on the RPi0.

After running "pip install picamera2", the version is still picamera2 0.3.12 and does not have the 'Num' key in the collection list
returned by the global_camera_info() method.

I guess I need to see if there is an updated picamera2 library I can install on bullseye.
What version does RasPyCam require?

**Comment by hogwell** [comment]
Adding this code in process.py's start_background_process got things going for me on bullseye!

        if "Num" not in c:
            c["Num"] = index

**Comment by kaihokori** [comment]
Hey @hogwell! You beat me to the punch 😄

It does seem that assigning `c["Num"] = index` when `"Num"` is missing effectively prevents the KeyError and enables the program to run smoothly without impacting other functionalities. 

I don't have access to a Pi device so I'll try hand this off to someone else to verify everything else remains unaffected (it should be all fine). 

Thanks again! 🎉

**Comment by hogwell** [comment]
Glad this was a good addition.

I'll play with the software more and report any other issues I see.

I'd like to add the timelapse (tl) functionality back, which I use quite a bit.

Great job!
