### ISSUE TITLE
Image button feedback not working

### ISSUE THREAD

**Issue by hogwell** [Windermere-Technology/RasPyCam#17]
### Description

When I click the Image button in the front-end, no visual feedback is given.
The interface normally changes the color of the Image button.

### Steps to Reproduce

Push the "take image" button in the frontend.

### Expected Behavior

The button should change color while the image is being captured.

### Additional Information (Optional)

_This is due to the status file not being set to "image" during the image capture.

### Pi Model

Zero

### Operating System

Raspberry Pi OS Bullseye (11.x)

### Checks

- [X] I have not found any related issues
- [X] I have updated to the latest version
- [X] I want to contribute a fix

**Comment by NhanDotJS** [comment]
Thank you for the fix, looks good to me. Merged!
