### ISSUE TITLE
No feed using RPi-Cam-Web-Interface

### ISSUE THREAD

**Issue by moataz-youssef** [Windermere-Technology/RasPyCam#19]
### Description

Long time user of RPi-Cam-Web-Interface here :-)
I wanted to give RasPyCam a go. I installed on top of a Raspberry Pi OS Lite (Debian 12, 64 bit) install using the default settings. RPi-Cam-Web-Interface was installed by answering with yes when prompted. Settings were kept at default. Now visiting IP-Address/html results in no output (see screenshot). As if there is no camera connected to the system.

Running `libcamera-hello --list-cameras` results in:
```
Available cameras
-----------------
0 : imx477 [4056x3040 12-bit RGGB] (/base/soc/i2c0mux/i2c@1/imx477@1a)
    Modes: 'SRGGB10_CSI2P' : 1332x990 [120.05 fps - (696, 528)/2664x1980 crop]
           'SRGGB12_CSI2P' : 2028x1080 [50.03 fps - (0, 440)/4056x2160 crop]
                             2028x1520 [40.01 fps - (0, 0)/4056x3040 crop]
                             4056x3040 [10.00 fps - (0, 0)/4056x3040 crop]
```

Running `raspimjpeg `gives:
`Launching raspycam with default configuration`
But there is no output in /tmp or /var/www/html/media

I am using a Raspberry Pi 4B with the original HQ Camera.

### Expected Behavior

I expect to get a live feed by running IP-Address/html as is the default behaviour in RPi-Cam-Web-Interface.

### Pi Model

4

### Operating System

Raspberry Pi OS Bookworm (12.x)

### Checks

- [X] I have not found any related issues
- [X] I have updated to the latest version
- [ ] I want to contribute a fix

**Comment by moataz-youssef** [comment]
![screenshot-2024 12 03-09_17_46](https://github.com/user-attachments/assets/92f4c010-0f75-4c06-b410-134ea2c4e991)

**Comment by hogwell** [comment]
See if there is any information in the log file:
tail /opt/vc/bin/raspycam/raspy.log

**Comment by moataz-youssef** [comment]
I get the following output:

```
moataz@RasPyCam:~ $ tail /opt/vc/bin/raspycam/raspy.log
    from core.process import start_background_process
  File "/opt/vc/bin/raspycam/core/process.py", line 8, in <module>
    from picamera2 import Picamera2
ModuleNotFoundError: No module named 'picamera2'
Traceback (most recent call last):
  File "/opt/vc/bin/raspycam/main.py", line 2, in <module>
    from core.process import start_background_process
  File "/opt/vc/bin/raspycam/core/process.py", line 8, in <module>
    from picamera2 import Picamera2
ModuleNotFoundError: No module named 'picamera2'
```

Should I install the package "python3-picamera2" via apt?

In the instructions, it was not clear that you need to pip install picamera2, as there it is written "if you want to run the source code" which I don't. So should I install picamera2 using pip or using apt?

**Comment by kaihokori** [comment]
Yes, you should install picamera2

Since mid 2022, all Raspberry Pi operating systems began shipping with this module preinstalled. That’s why it’s not included in the instructions. 

You might have done something funky to your package manager 🤔

**Comment by moataz-youssef** [comment]
I will install it then. Thanks a lot. apt or pip?

It is very strange that I don't have it by default. This is a standard RPi OS Lite 64bit install through the RPi Imager program.

**Comment by kaihokori** [comment]
I’m not too sure on which one should be used. Probably depends on whether your packages are externally managed. 

For pip, the command is actually in the instructions (didn’t realise I included it). For apt, try this: 

`sudo apt install -y python3-picamera2 `

**Comment by kaihokori** [comment]
If you’re using pip or pip3, maybe look at this: 

https://forums.raspberrypi.com/viewtopic.php?t=361758

EDIT: I gave the wrong link. This is the correct one.

**Comment by moataz-youssef** [comment]
Installed using apt and then restarted. Works great. I will do further testing and report how it compares to the good old RPi-Cam-Web-Interface.
