### ISSUE TITLE
%a not supported in annotation format string

### ISSUE THREAD

**Issue by hogwell** [Windermere-Technology/RasPyCam#3]
### Description

The %a format specifier should be supported in the Annotation Camera Settings, as
in the original raspimjpeg back end module.

### Additional Information (Optional)

This feature originally worked in raspimjpeg by including the contents of this file in the formatted annotation string shown at the top of the camera image.

/dev/shm/mjpeg/user_annotate.txt

### Checks

- [X] I have not found any related feature requests
- [X] I have not found this feature in the application
- [ ] I want to contribute to the development of this feature

**Comment by kaihokori** [comment]
A pull request has been made (#3). Just waiting on someone to review 👍
