### ISSUE TITLE
"sy" macro execution command is missing

### ISSUE THREAD

**Issue by hogwell** [Windermere-Technology/RasPyCam#9]
### Description

The 'sy' command to execute a macro should be implemented.

The command syntax is:
"""
sy somemacro.sh [args...]
"""

This should execute the script named "/var/www/html/macros/somemacro.sh <args>"
as the correct user (e.g. www-data).

### Additional Information (Optional)

Use cases:

In the Rpi_Cam_Web_Interface the 'sy' command is often used to customize both user buttons and scheduler actions.

For example, I have a script "mktimelapse.sh" that will combine any timelapse filesets into mp4 video files, delete the .jpg files, upload the mp4 to my ftp server, then delete the mp4 filel.
I configure a scheduled action as: "sy mktimelapse.sh 3" in Rpi_Cam_Web_Interface to run this every night.

Something like this could also be used to upload motion-detect videos each night, too.

This kind of thing is used by users for all kinds of things to customize Rpi_Cam_Web_Interface.
It is one of the best features of Rpi_Cam_Web_Interface, I think...

### Checks

- [X] I have not found any related feature requests
- [X] I have not found this feature in the application
- [X] #10

**Comment by kaihokori** [comment]
A pull request has been made #11. Just waiting on someone to review 👍
